In [1]:
import tensorflow as tf

In [3]:
print("Num GPUs Available: ", len(tf.config.experimental.list_physical_devices('GPU')))

Num GPUs Available:  1


In [4]:
x = tf.constant(4.0)

In [6]:
print(x)

tf.Tensor(4.0, shape=(), dtype=float32)


In [10]:
y = tf.constant([[1,2,3],[4,2,1]])
y

<tf.Tensor: id=3, shape=(2, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [4, 2, 1]])>

#### -->Just like numpy initializations

In [14]:
z = tf.random.normal((3,3,3),mean=0,stddev=1)

In [15]:
print(z)

tf.Tensor(
[[[-0.6824199  -0.41427487  0.16091858]
  [-0.72719705  1.0424352   0.7592243 ]
  [ 1.9451311   2.2089913  -0.9282057 ]]

 [[-0.88537306 -0.47641122  0.55520654]
  [-0.22675516  0.51024985 -0.88210815]
  [-0.5254105   1.1817789  -1.9820209 ]]

 [[ 0.5696297  -0.6822766  -0.87543494]
  [-0.14611481  0.9780775  -0.6245955 ]
  [-0.07699865 -0.32815763 -0.7827316 ]]], shape=(3, 3, 3), dtype=float32)


In [17]:
z = tf.random.uniform((2,2,2),minval=0,maxval=10)

In [18]:
print(z)

tf.Tensor(
[[[5.9894156 3.550799 ]
  [6.1129665 3.4036827]]

 [[1.1242628 8.941535 ]
  [9.808513  4.136466 ]]], shape=(2, 2, 2), dtype=float32)


In [20]:
tf.cast(z,dtype=tf.float64)

<tf.Tensor: id=23, shape=(2, 2, 2), dtype=float64, numpy=
array([[[5.98941565, 3.55079889],
        [6.11296654, 3.40368271]],

       [[1.12426281, 8.941535  ],
        [9.80851269, 4.13646603]]])>

In [21]:
p = tf.random.uniform((2,2,2))

In [22]:
p

<tf.Tensor: id=30, shape=(2, 2, 2), dtype=float32, numpy=
array([[[0.00948656, 0.247262  ],
        [0.10648489, 0.29891837]],

       [[0.6817936 , 0.77089703],
        [0.7783725 , 0.01404262]]], dtype=float32)>

In [23]:
new = tf.add(z,p)

In [24]:
new

<tf.Tensor: id=31, shape=(2, 2, 2), dtype=float32, numpy=
array([[[ 5.9989023,  3.798061 ],
        [ 6.2194514,  3.702601 ]],

       [[ 1.8060564,  9.712432 ],
        [10.586885 ,  4.150509 ]]], dtype=float32)>

In [25]:
dot= tf.tensordot(z,p,axes=1) #LIKE MATRIX MULTIPLICATION

In [26]:
dot # (2,2),2 * 2,(2,2) = 2,2,2,2

<tf.Tensor: id=42, shape=(2, 2, 2, 2), dtype=float32, numpy=
array([[[[2.4777308 , 4.218255  ],
         [3.4016266 , 1.8402089 ]],

        [[2.3786001 , 4.135393  ],
         [3.3002715 , 1.8750746 ]]],


       [[[6.1069465 , 7.1709905 ],
         [7.079562  , 0.46162534]],

        [[2.913265  , 5.614062  ],
         [4.2641697 , 2.9900315 ]]]], dtype=float32)>

In [27]:
at = z@p #element wise mul

In [28]:
at

<tf.Tensor: id=43, shape=(2, 2, 2), dtype=float32, numpy=
array([[[0.43492535, 2.5423539 ],
        [0.42043176, 2.5289276 ]],

       [[7.7263603 , 0.9922534 ],
        [9.907092  , 7.61944   ]]], dtype=float32)>